### ISSUE TITLE
About Docker

### ISSUE THREAD

**Issue by s1710335** [SysCV/spc2#9]
Can you please provide a Docker environment with spc2 pre-installed and ready to run?

**Comment by noahcao** [comment]
that has been mentioned in readme, please try:

> docker pull deepdrive/spc

**Comment by s1710335** [comment]
How do I install spc2 when using Docker? Should I put spc2 in the container I created (deepdrive/spc) and use it?
Is it enough to put spc2 in the container I created (deepdrive/spc), or should I put spc2 in a local environment separate from docker and let it communicate with the simulator-side (deepdrive/spc)?
Thank you very much for your help.
